### ISSUE TITLE
When use kernelcode build for myself mix 4.....

### ISSUE THREAD

**Issue by QiuChenly** [Inkypen79/kernel_xiaomi_odin#2]
Hello! Hero Inkypen79 !

When compiling using this kernel source code, I was able to compile the successful Image and dtbo.img (without modifying the source code), but when I tried to package these two files with Anykernel3 and flash them into my phone, he encountered a startup loop

I flashed into your EvolutionX 14.0, but what confuses me is that I tried to add KernelSU support in the source code, but only compiled the kernel source code and encountered a startup loop. Can you help me solve this problem?

How can I compile a kernel that can boot the system normally? Based on the information I have searched, if you only want to compile the kernel and start EvolutionX on your own, you should not encounter startup issues I don't know where I went wrong:（

I'm sorry, I'm a beginner and I'm currently learning:（

**Comment by QiuChenly** [comment]
<img width="1904" alt="image" src="https://github.com/Inkypen79/kernel_xiaomi_odin/assets/24793281/19cb9ed0-f87b-4c96-8eec-2fc333a29a9a">

**Comment by Inkypen79** [comment]
There isn't enough information to determine what the problem is. Could be the difference between compiling with gcc or clang, different vermagic signature of kernel modules or corrupted ramdisk in boot image.  You will need to do logging to find the cause of the issue. Either logcat, dmesg ramoops or mtdoops logs should help.
